name: kairos-dex qa deploy workflow
on:
  push:
    branches:
      - test

env:
  PROJECT_ID: "kaia-cluster-dev"
  SERVICE_ACCOUNT: "kairos-dex-qa@kaia-cluster-dev.iam.gserviceaccount.com"
  WORKLOAD_IDENTITY_PROVIDER: "projects/383360562319/locations/global/workloadIdentityPools/kaia-cluster-dev/providers/kairos-dex"

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.12.0'

      - name: Install dependencies
        run: |
          yarn install 

      - name: Create .env from GCP Secret Manager
        run: |
          gcloud secrets versions access latest --secret="kairos-dex-qa" --project="${{ env.PROJECT_ID }}" | \
          jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > .env

      - name: Build static files
        run: yarn build

      - name: Deploy to GCS
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'dist'
          destination: 'kairos-dex-qa'
          parent: false

      - name: Invalid CDN cache on GCP
        uses: stefanodotit/github-actions-invalidate-gcp-cdn@v1
        with:
            load_balancer_name: kairos-dex-qa
            path: '/*'
            host: 'kairos-dex.qa.kaia.io'
